#ifndef EVENT_DEFINES_H
#define EVENT_DEFINES_H

enum AhnQirajIDs
{
    EVENT_ID = 1,
    QUEST_ALLIANCE_ARTHAS_TEARS = 8510
};

enum AhnQuirajResources
{
    COPPER_BAR = 0,
    PURPLE_LOTUS = 1,
    THICK_LEATHER = 2,
    SPOTTED_YELLOWTAIL = 3,
    RUNECLOTH_BANDAGE = 4,
    IRON_BAR = 5,
    THORIUM_BAR = 6,
    ARTHAS_TEARS = 7,
    STRANGLEKELP = 8,
    LIGHT_LEATHER = 9,
    MEDIUM_LEATHER = 10,
    ROAST_RAPTOR = 11,
    RAINBOW_FIN_ALBACORE = 12,
    LINEN_BANDAGE = 13,
    SILK_BANDAGE = 14,
    TIN_BAR = 15,
    MITHRIL_BAR = 16,
    PEACEBLOOM = 17,
    FIREBLOOM = 18,
    HEAVY_LEATHER = 19,
    RUGGED_LEATHER = 20,
    LEAN_WOLF_STEAK = 21,
    BAKED_SALMON = 22,
    WOOL_BANDAGE = 23,
    MAGEWEAVE_BANDAGE = 24
};

#endif
